Percona-Lab/percona-version-service

.gitignore
versionpb/go.mod
versionpb/hack.go

Create a submodule inside proto file directory to be able to fetch it from other projects with go modules

add go module to version proto

---

sources/operator.1.5.0.pxc-operator.json

Adds PXC 5.7.30 and 8.0.18 into json file for operator 1.5.0

Add PXC 5.7.30 and 8.0.18 into json file

---

sources/operator.1.7.0.pxc-operator.json

Notice that I'm merging this to not to master branch but to pxco-release-170 from which I'll build VS image since I don't want to include last change from master branch for this release.

Update PXCO backup image hashes

---

sources/pmm.2.22.0.pmm-server.json

PMM 2.22.0 is under development.

Add dependencies for PMM 2.22.0

---

sources/pmm.2.24.0.pmm-server.json

PMM 2.23.0 RC will be cut today, new development cycle begins afterwards.

Prepare for PMM 2.24.0 development cycle

---

README.md

Fixed some spelling/grammar/consistency issues.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>

README.md: small textual improvements

---

sources/pmm.2.27.0.pmm-server.json
sources/pmm.2.28.0.pmm-server.json
sources/pmm.2.30.0.pmm-server.json

For QA.
We need to test PXC operator 1.11 in PMM 2.27 ~ 2.30

PMM-10085 Defined PXC operator 1.11 for some pmm versions

---

sources/pmm.2.29.1.pmm-server.json

it's a cherry-pick of my previous PR to development environment (#81)

PMM-10444 Add PMM 2.29.1 (#81)

---

api/version.proto
api/version.swagger.yaml
third_party/OpenAPI/api/version.swagger.yaml

This was merged to `main`, but we forgot to merge it to `production`.

K8SPSMDB-719: Add more telemetry fields

---

sources/pmm.2.31.0.pmm-server.json
sources/pmm.2.32.0.pmm-server.json

Reverts Percona-Lab/percona-version-service#98

Revert "PMM-10724 Added custom pxc operator version with fixes for civo provider"

---

sources/operator.1.12.0.pxc-operator.dep.json
sources/operator.1.12.0.pxc-operator.json

Version is correct, image label is wrong.

K8SPXC-1165 - Fix version for PXC 1.12.0 backup image

---

sources/metadata/everest/0.8.0.yaml

Deploy first Everest version in dev environment
EVEREST-793

EVEREST-793: first Everest version

---

sources/metadata/everest/1.0.0-rc2.yaml

Everest 1.0.0-rc2

---

sources/metadata/everest/1.0.0-rc3.yaml

Everest 1.0.0-rc3

---

sources/metadata/everest/1.0.0-rc4.yaml

Everest 1.0.0-rc4

---

sources/metadata/everest/1.0.0-rc5.yaml

Everest 1.0.0-rc5

---

sources/metadata/everest/1.0.0-rc6.yaml

Everest 1.0.0-rc6
Opening the PR in case we would need it, to have it unblocked, with 2 approval, ready to be merged

Everest 1.0.0-rc6

---

sources/metadata/everest/1.0.0.yaml

Add Everest 1.0.0 to production

Everest prod 1.0.0

---

sources/metadata/everest/1.0.0.yaml

Everest dev 1.0.0

---

sources/metadata/pmm-server/3.1.0.yaml
sources/release-notes/pmm/3.1.0.md

Post new PMM update available info for 3.1.0 RC testing purposes

PMM-13796: Add 3.1.0 RN to Dev

---

sources/metadata/pmm-server/3.1.0.yaml
sources/release-notes/pmm/3.1.0.md

Publishing 3.1.0 and RN content

PMM-13796 - 3.1.0 Release notes content for Version service

---

sources/metadata/pmm-server/3.2.0.yaml
sources/metadata/pmm-server/3.3.0.yaml
sources/release-notes/pmm/3.2.0.md
sources/release-notes/pmm/3.3.0.md

PMM-13902 3.2.0 update version service to Dev

PMM-13902 3.2.0 update Version service for Stage

---

api-tests/apply_route_test.go
sources/operator.0.10.0.ps-operator.json
sources/operator.1.17.0.pxc-operator.json
sources/operator.1.20.1.psmdb-operator.json
sources/operator.2.7.0.pg-operator.json

* Upgrade PMM client
* tests fix
* Add pmm 3.3.1
* fix tests
---------

Upgrade PMM client (#423)
